### ISSUE TITLE
Using images rather than DeepZoom doesnt seem to work

### ISSUE THREAD

**Issue by genvej** [openlink/html5pivotviewer#34]
Hi. Great tool!!

I got everything running on my IIS. All the samples except the ones with images work fine. Is this a known issue or am i missing the obvious?

Keep up the good work!

**Comment by rnp716** [comment]
I had similar problems. I think it's a bug in the way simpleimage.js is written. It calculates values such as "Ratio" before the images are fully loaded, which therefore results in NaN in all further calculations involving those images.

**Comment by JacquiHand** [comment]
This should now be fixed.  Let me know if it is still a problem.
